<?php
namespace Database\Seeders;

use App\Models\Books;
use App\Models\Category;
use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class BooksSeeder extends Seeder
{
    public function run()
    {
        Books::insert([
            [
                'title' => 'Книга 1',
                'slug'  => 'book-1',
                'author' => 'Автор книги 1',
                'description' => 'Описание книги 1',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '1',
            ],
            [
                'title' => 'Книга 2',
                'slug'  => 'book-2',
                'author' => 'Автор книги 2',
                'description' => 'Описание книги 2',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '1',
            ],
            [
                'title' => 'Книга 3',
                'slug'  => 'book-3',
                'author' => 'Автор книги 3',
                'description' => 'Описание книги 3',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '1'
            ],
            [
                'title' => 'Книга 4',
                'slug'  => 'book-4',
                'author' => 'Автор книги 4',
                'description' => 'Описание книги 4',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '1',
            ],
            [
                'title' => 'Книга 5',
                'slug'  => 'book-5',
                'author' => 'Автор книги 5',
                'description' => 'Описание книги 5',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '1',
            ],
            [
                'title' => 'Книга 6',
                'slug'  => 'book-6',
                'author' => 'Автор книги 6',
                'description' => 'Описание книги 6',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '1',
            ],
            [
                'title' => 'Книга 7',
                'slug'  => 'book-7',
                'author' => 'Автор книги 7',
                'description' => 'Описание книги 7',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '1',
            ],
            [
                'title' => 'Книга 8',
                'slug'  => 'book-8',
                'author' => 'Автор книги 8',
                'description' => 'Описание книги 8',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '1'
            ],
            [
                'title' => 'Книга 9',
                'slug'  => 'book-9',
                'author' => 'Автор книги 9',
                'description' => 'Описание книги 9',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '1',
            ],
            [
                'title' => 'Книга 10',
                'slug'  => 'book-10',
                'author' => 'Автор книги 10',
                'description' => 'Описание книги 10',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '1',
            ],
            [
                'title' => 'Книга 11',
                'slug'  => 'book-11',
                'author' => 'Автор книги 11',
                'description' => 'Описание книги 11',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '1',
            ],
            [
                'title' => 'Книга 12',
                'slug'  => 'book-12',
                'author' => 'Автор книги 12',
                'description' => 'Описание книги 12',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '1',
            ],
            [
                'title' => 'Книга 13',
                'slug'  => 'book-13',
                'author' => 'Автор книги 13',
                'description' => 'Описание книги 13',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '1'
            ],
            [
                'title' => 'Книга 14',
                'slug'  => 'book-14',
                'author' => 'Автор книги 14',
                'description' => 'Описание книги 14',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '1',
            ],
            [
                'title' => 'Книга 15',
                'slug'  => 'book-15',
                'author' => 'Автор книги 15',
                'description' => 'Описание книги 15',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '1',
            ],
            [
                'title' => 'Книга 16',
                'slug'  => 'book-16',
                'author' => 'Автор книги 16',
                'description' => 'Описание книги 16',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '1',
            ],
            [
                'title' => 'Книга 17',
                'slug'  => 'book-17',
                'author' => 'Автор книги 17',
                'description' => 'Описание книги 17',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '1',
            ],
            [
                'title' => 'Книга 18',
                'slug'  => 'book-18',
                'author' => 'Автор книги 18',
                'description' => 'Описание книги 18',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '1'
            ],
            [
                'title' => 'Книга 19',
                'slug'  => 'book-19',
                'author' => 'Автор книги 19',
                'description' => 'Описание книги 19',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '1',
            ],
            [
                'title' => 'Книга 20',
                'slug'  => 'book-20',
                'author' => 'Автор книги 20',
                'description' => 'Описание книги 20',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '1',
            ],
            [
                'title' => 'Книга 21',
                'slug'  => 'book-21',
                'author' => 'Автор книги 21',
                'description' => 'Описание книги 21',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '2',
            ],
            [
                'title' => 'Книга 22',
                'slug'  => 'book-22',
                'author' => 'Автор книги 22',
                'description' => 'Описание книги 22',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '2',
            ],
            [
                'title' => 'Книга 23',
                'slug'  => 'book-23',
                'author' => 'Автор книги 23',
                'description' => 'Описание книги 23',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '2'
            ],
            [
                'title' => 'Книга 24',
                'slug'  => 'book-24',
                'author' => 'Автор книги 24',
                'description' => 'Описание книги 24',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '2',
            ],
            [
                'title' => 'Книга 25',
                'slug'  => 'book-25',
                'author' => 'Автор книги 25',
                'description' => 'Описание книги 25',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '2',
            ],
            [
                'title' => 'Книга 26',
                'slug'  => 'book-26',
                'author' => 'Автор книги 26',
                'description' => 'Описание книги 26',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '2',
            ],
            [
                'title' => 'Книга 27',
                'slug'  => 'book-27',
                'author' => 'Автор книги 27',
                'description' => 'Описание книги 27',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '2',
            ],
            [
                'title' => 'Книга 28',
                'slug'  => 'book-28',
                'author' => 'Автор книги 28',
                'description' => 'Описание книги 28',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '2'
            ],
            [
                'title' => 'Книга 29',
                'slug'  => 'book-29',
                'author' => 'Автор книги 29',
                'description' => 'Описание книги 29',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '2',
            ],
            [
                'title' => 'Книга 30',
                'slug'  => 'book-30',
                'author' => 'Автор книги 30',
                'description' => 'Описание книги 30',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '2',
            ],
            [
                'title' => 'Книга 31',
                'slug'  => 'book-31',
                'author' => 'Автор книги 31',
                'description' => 'Описание книги 31',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '2',
            ],
            [
                'title' => 'Книга 32',
                'slug'  => 'book-32',
                'author' => 'Автор книги 32',
                'description' => 'Описание книги 32',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '2',
            ],
            [
                'title' => 'Книга 33',
                'slug'  => 'book-33',
                'author' => 'Автор книги 33',
                'description' => 'Описание книги 33',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '2'
            ],
            [
                'title' => 'Книга 34',
                'slug'  => 'book-34',
                'author' => 'Автор книги 34',
                'description' => 'Описание книги 34',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '2',
            ],
            [
                'title' => 'Книга 35',
                'slug'  => 'book-35',
                'author' => 'Автор книги 35',
                'description' => 'Описание книги 35',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '2',
            ],
            [
                'title' => 'Книга 36',
                'slug'  => 'book-36',
                'author' => 'Автор книги 36',
                'description' => 'Описание книги 36',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '2',
            ],
            [
                'title' => 'Книга 37',
                'slug'  => 'book-37',
                'author' => 'Автор книги 37',
                'description' => 'Описание книги 37',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '2',
            ],
            [
                'title' => 'Книга 38',
                'slug'  => 'book-38',
                'author' => 'Автор книги 38',
                'description' => 'Описание книги 38',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '2'
            ],
            [
                'title' => 'Книга 39',
                'slug'  => 'book-39',
                'author' => 'Автор книги 39',
                'description' => 'Описание книги 39',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '2',
            ],
            [
                'title' => 'Книга 40',
                'slug'  => 'book-40',
                'author' => 'Автор книги 40',
                'description' => 'Описание книги 40',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '2',
            ],
            [
                'title' => 'Книга 41',
                'slug'  => 'book-41',
                'author' => 'Автор книги 41',
                'description' => 'Описание книги 41',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '3',
            ],
            [
                'title' => 'Книга 42',
                'slug'  => 'book-42',
                'author' => 'Автор книги 42',
                'description' => 'Описание книги 42',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '3',
            ],
            [
                'title' => 'Книга 43',
                'slug'  => 'book-43',
                'author' => 'Автор книги 43',
                'description' => 'Описание книги 43',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '3',
            ],
            [
                'title' => 'Книга 44',
                'slug'  => 'book-44',
                'author' => 'Автор книги 44',
                'description' => 'Описание книги 44',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '3'
            ],
            [
                'title' => 'Книга 45',
                'slug'  => 'book-45',
                'author' => 'Автор книги 45',
                'description' => 'Описание книги 45',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '3',
            ],
            [
                'title' => 'Книга 46',
                'slug'  => 'book-46',
                'author' => 'Автор книги 46',
                'description' => 'Описание книги 46',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '3',
            ],
            [
                'title' => 'Книга 47',
                'slug'  => 'book-47',
                'author' => 'Автор книги 47',
                'description' => 'Описание книги 47',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '3',
            ],
            [
                'title' => 'Книга 48',
                'slug'  => 'book-48',
                'author' => 'Автор книги 48',
                'description' => 'Описание книги 48',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '3',
            ],
            [
                'title' => 'Книга 49',
                'slug'  => 'book-49',
                'author' => 'Автор книги 49',
                'description' => 'Описание книги 49',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '3'
            ],
            [
                'title' => 'Книга 50',
                'slug'  => 'book-50',
                'author' => 'Автор книги 50',
                'description' => 'Описание книги 50',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '3',
            ],
            [
                'title' => 'Книга 51',
                'slug'  => 'book-51',
                'author' => 'Автор книги 51',
                'description' => 'Описание книги 51',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '3',
            ],
            [
                'title' => 'Книга 52',
                'slug'  => 'book-52',
                'author' => 'Автор книги 52',
                'description' => 'Описание книги 52',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '3',
            ],
            [
                'title' => 'Книга 53',
                'slug'  => 'book-53',
                'author' => 'Автор книги 53',
                'description' => 'Описание книги 53',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '3',
            ],
            [
                'title' => 'Книга 54',
                'slug'  => 'book-54',
                'author' => 'Автор книги 54',
                'description' => 'Описание книги 54',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '3'
            ],
            [
                'title' => 'Книга 55',
                'slug'  => 'book-55',
                'author' => 'Автор книги 55',
                'description' => 'Описание книги 55',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '3',
            ],
            [
                'title' => 'Книга 56',
                'slug'  => 'book-56',
                'author' => 'Автор книги 56',
                'description' => 'Описание книги 56',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '3',
            ],
            [
                'title' => 'Книга 57',
                'slug'  => 'book-57',
                'author' => 'Автор книги 57',
                'description' => 'Описание книги 57',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '3',
            ],
            [
                'title' => 'Книга 58',
                'slug'  => 'book-58',
                'author' => 'Автор книги 58',
                'description' => 'Описание книги 58',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '3',
            ],
            [
                'title' => 'Книга 59',
                'slug'  => 'book-59',
                'author' => 'Автор книги 59',
                'description' => 'Описание книги 59',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '3'
            ],
            [
                'title' => 'Книга 60',
                'slug'  => 'book-60',
                'author' => 'Автор книги 60',
                'description' => 'Описание книги 60',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '3',
            ],
            [
                'title' => 'Книга 61',
                'slug'  => 'book-61',
                'author' => 'Автор книги 61',
                'description' => 'Описание книги 61',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '4',
            ],
            [
                'title' => 'Книга 62',
                'slug'  => 'book-62',
                'author' => 'Автор книги 62',
                'description' => 'Описание книги 62',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '4',
            ],
            [
                'title' => 'Книга 63',
                'slug'  => 'book-63',
                'author' => 'Автор книги 63',
                'description' => 'Описание книги 63',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '4',
            ],
            [
                'title' => 'Книга 65',
                'slug'  => 'book-65',
                'author' => 'Автор книги 65',
                'description' => 'Описание книги 65',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '4',
            ],
            [
                'title' => 'Книга 66',
                'slug'  => 'book-66',
                'author' => 'Автор книги 66',
                'description' => 'Описание книги 66',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '4'
            ],
            [
                'title' => 'Книга 67',
                'slug'  => 'book-67',
                'author' => 'Автор книги 67',
                'description' => 'Описание книги 67',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '4',
            ],
            [
                'title' => 'Книга 68',
                'slug'  => 'book-68',
                'author' => 'Автор книги 68',
                'description' => 'Описание книги 68',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '4',
            ],
            [
                'title' => 'Книга 69',
                'slug'  => 'book-69',
                'author' => 'Автор книги 69',
                'description' => 'Описание книги 69',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '4',
            ],
            [
                'title' => 'Книга 70',
                'slug'  => 'book-70',
                'author' => 'Автор книги 70',
                'description' => 'Описание книги 70',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '4',
            ],
            [
                'title' => 'Книга 71',
                'slug'  => 'book-71',
                'author' => 'Автор книги 71',
                'description' => 'Описание книги 71',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '4'
            ],
            [
                'title' => 'Книга 72',
                'slug'  => 'book-72',
                'author' => 'Автор книги 72',
                'description' => 'Описание книги 72',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '4',
            ],
            [
                'title' => 'Книга 73',
                'slug'  => 'book-73',
                'author' => 'Автор книги 73',
                'description' => 'Описание книги 73',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '4',
            ],
            [
                'title' => 'Книга 74',
                'slug'  => 'book-74',
                'author' => 'Автор книги 74',
                'description' => 'Описание книги 74',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '4',
            ],
            [
                'title' => 'Книга 75',
                'slug'  => 'book-75',
                'author' => 'Автор книги 75',
                'description' => 'Описание книги 75',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '4',
            ],
            [
                'title' => 'Книга 76',
                'slug'  => 'book-76',
                'author' => 'Автор книги 76',
                'description' => 'Описание книги 76',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '4'
            ],
            [
                'title' => 'Книга 77',
                'slug'  => 'book-77',
                'author' => 'Автор книги 77',
                'description' => 'Описание книги 77',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '4',
            ],
            [
                'title' => 'Книга 78',
                'slug'  => 'book-78',
                'author' => 'Автор книги 78',
                'description' => 'Описание книги 78',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '4',
            ],
            [
                'title' => 'Книга 79',
                'slug'  => 'book-79',
                'author' => 'Автор книги 79',
                'description' => 'Описание книги 79',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '4',
            ],
            [
                'title' => 'Книга 80',
                'slug'  => 'book-80',
                'author' => 'Автор книги 80',
                'description' => 'Описание книги 80',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '4',
            ],
            [
                'title' => 'Книга 81',
                'slug'  => 'book-81',
                'author' => 'Автор книги 81',
                'description' => 'Описание книги 81',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '5'
            ],
            [
                'title' => 'Книга 82',
                'slug'  => 'book-82',
                'author' => 'Автор книги 82',
                'description' => 'Описание книги 82',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '5',
            ],
            [
                'title' => 'Книга 83',
                'slug'  => 'book-83',
                'author' => 'Автор книги 83',
                'description' => 'Описание книги 83',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '5',
            ],
            [
                'title' => 'Книга 84',
                'slug'  => 'book-84',
                'author' => 'Автор книги 84',
                'description' => 'Описание книги 84',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '5',
            ],
            [
                'title' => 'Книга 85',
                'slug'  => 'book-85',
                'author' => 'Автор книги 85',
                'description' => 'Описание книги 85',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '5',
            ],
            [
                'title' => 'Книга 86',
                'slug'  => 'book-86',
                'author' => 'Автор книги 86',
                'description' => 'Описание книги 86',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '5',
            ],
            [
                'title' => 'Книга 87',
                'slug'  => 'book-87',
                'author' => 'Автор книги 87',
                'description' => 'Описание книги 87',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '5'
            ],
            [
                'title' => 'Книга 88',
                'slug'  => 'book-88',
                'author' => 'Автор книги 88',
                'description' => 'Описание книги 88',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '5',
            ],
            [
                'title' => 'Книга 89',
                'slug'  => 'book-89',
                'author' => 'Автор книги 89',
                'description' => 'Описание книги 89',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '5',
            ],
            [
                'title' => 'Книга 90',
                'slug'  => 'book-90',
                'author' => 'Автор книги 90',
                'description' => 'Описание книги 90',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '5',
            ],
            [
                'title' => 'Книга 91',
                'slug'  => 'book-91',
                'author' => 'Автор книги 91',
                'description' => 'Описание книги 91',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '5',
            ],
            [
                'title' => 'Книга 92',
                'slug'  => 'book-92',
                'author' => 'Автор книги 92',
                'description' => 'Описание книги 92',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '5'
            ],
            [
                'title' => 'Книга 93',
                'slug'  => 'book-93',
                'author' => 'Автор книги 93',
                'description' => 'Описание книги 93',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '5',
            ],
            [
                'title' => 'Книга 94',
                'slug'  => 'book-94',
                'author' => 'Автор книги 94',
                'description' => 'Описание книги 94',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '5',
            ],
            [
                'title' => 'Книга 95',
                'slug'  => 'book-95',
                'author' => 'Автор книги 95',
                'description' => 'Описание книги 95',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '5',
            ],
            [
                'title' => 'Книга 96',
                'slug'  => 'book-96',
                'author' => 'Автор книги 96',
                'description' => 'Описание книги 96',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '5',
            ],
            [
                'title' => 'Книга 97',
                'slug'  => 'book-97',
                'author' => 'Автор книги 97',
                'description' => 'Описание книги 97',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '5'
            ],
            [
                'title' => 'Книга 98',
                'slug'  => 'book-98',
                'author' => 'Автор книги 98',
                'description' => 'Описание книги 98',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '5',
            ],
            [
                'title' => 'Книга 99',
                'slug'  => 'book-99',
                'author' => 'Автор книги 99',
                'description' => 'Описание книги 99',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '5',
            ],
            [
                'title' => 'Книга 100',
                'slug'  => 'book-100',
                'author' => 'Автор книги 100',
                'description' => 'Описание книги 100',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '5',
            ],
            [
                'title' => 'Книга 101',
                'slug'  => 'book-101',
                'author' => 'Автор книги 101',
                'description' => 'Описание книги 101',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '6',
            ],
            [
                'title' => 'Книга 102',
                'slug'  => 'book-102',
                'author' => 'Автор книги 102',
                'description' => 'Описание книги 102',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '6'
            ],
            [
                'title' => 'Книга 103',
                'slug'  => 'book-103',
                'author' => 'Автор книги 103',
                'description' => 'Описание книги 103',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '6',
            ],
            [
                'title' => 'Книга 104',
                'slug'  => 'book-104',
                'author' => 'Автор книги 104',
                'description' => 'Описание книги 104',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '6',
            ],
            [
                'title' => 'Книга 105',
                'slug'  => 'book-105',
                'author' => 'Автор книги 105',
                'description' => 'Описание книги 105',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '6',
            ],
            [
                'title' => 'Книга 106',
                'slug'  => 'book-106',
                'author' => 'Автор книги 106',
                'description' => 'Описание книги 106',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '6'
            ],
            [
                'title' => 'Книга 107',
                'slug'  => 'book-107',
                'author' => 'Автор книги 107',
                'description' => 'Описание книги 107',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '6',
            ],
            [
                'title' => 'Книга 108',
                'slug'  => 'book-108',
                'author' => 'Автор книги 108',
                'description' => 'Описание книги 108',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '6',
            ],
            [
                'title' => 'Книга 109',
                'slug'  => 'book-109',
                'author' => 'Автор книги 109',
                'description' => 'Описание книги 109',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '6',
            ],
            [
                'title' => 'Книга 110',
                'slug'  => 'book-110',
                'author' => 'Автор книги 110',
                'description' => 'Описание книги 110',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '6'
            ],
            [
                'title' => 'Книга 111',
                'slug'  => 'book-111',
                'author' => 'Автор книги 111',
                'description' => 'Описание книги 111',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '6',
            ],
            [
                'title' => 'Книга 112',
                'slug'  => 'book-112',
                'author' => 'Автор книги 112',
                'description' => 'Описание книги 112',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '6',
            ],
            [
                'title' => 'Книга 113',
                'slug'  => 'book-113',
                'author' => 'Автор книги 113',
                'description' => 'Описание книги 113',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '6',
            ],
            [
                'title' => 'Книга 114',
                'slug'  => 'book-114',
                'author' => 'Автор книги 114',
                'description' => 'Описание книги 114',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '6'
            ],
            [
                'title' => 'Книга 115',
                'slug'  => 'book-115',
                'author' => 'Автор книги 115',
                'description' => 'Описание книги 115',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '6',
            ],
            [
                'title' => 'Книга 116',
                'slug'  => 'book-116',
                'author' => 'Автор книги 116',
                'description' => 'Описание книги 116',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '6',
            ],
            [
                'title' => 'Книга 117',
                'slug'  => 'book-117',
                'author' => 'Автор книги 117',
                'description' => 'Описание книги 117',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '6',
            ],
            [
                'title' => 'Книга 118',
                'slug'  => 'book-118',
                'author' => 'Автор книги 118',
                'description' => 'Описание книги 118',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '6',
            ],
            [
                'title' => 'Книга 119',
                'slug'  => 'book-119',
                'author' => 'Автор книги 119',
                'description' => 'Описание книги 119',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '6'
            ],
            [
                'title' => 'Книга 120',
                'slug'  => 'book-120',
                'author' => 'Автор книги 120',
                'description' => 'Описание книги 120',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '6',
            ],
            [
                'title' => 'Книга 121',
                'slug'  => 'book-121',
                'author' => 'Автор книги 121',
                'description' => 'Описание книги 121',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '7',
            ],
            [
                'title' => 'Книга 122',
                'slug'  => 'book-122',
                'author' => 'Автор книги 122',
                'description' => 'Описание книги 122',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '7',
            ],
            [
                'title' => 'Книга 123',
                'slug'  => 'book-123',
                'author' => 'Автор книги 123',
                'description' => 'Описание книги 123',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '7',
            ],
            [
                'title' => 'Книга 124',
                'slug'  => 'book-124',
                'author' => 'Автор книги 124',
                'description' => 'Описание книги 124',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '7',
            ],
            [
                'title' => 'Книга 125',
                'slug'  => 'book-125',
                'author' => 'Автор книги 125',
                'description' => 'Описание книги 125',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '7',
            ],
            [
                'title' => 'Книга 126',
                'slug'  => 'book-126',
                'author' => 'Автор книги 126',
                'description' => 'Описание книги 126',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '7',
            ],
            [
                'title' => 'Книга 127',
                'slug'  => 'book-127',
                'author' => 'Автор книги 127',
                'description' => 'Описание книги 127',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '7',
            ],
            [
                'title' => 'Книга 128',
                'slug'  => 'book-128',
                'author' => 'Автор книги 128',
                'description' => 'Описание книги 128',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '7',
            ],
            [
                'title' => 'Книга 129',
                'slug'  => 'book-129',
                'author' => 'Автор книги 129',
                'description' => 'Описание книги 129',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '7',
            ],
            [
                'title' => 'Книга 130',
                'slug'  => 'book-130',
                'author' => 'Автор книги 130',
                'description' => 'Описание книги 130',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '7',
            ],
            [
                'title' => 'Книга 131',
                'slug'  => 'book-131',
                'author' => 'Автор книги 131',
                'description' => 'Описание книги 131',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '7',
            ],
            [
                'title' => 'Книга 132',
                'slug'  => 'book-132',
                'author' => 'Автор книги 132',
                'description' => 'Описание книги 132',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '7',
            ],
            [
                'title' => 'Книга 133',
                'slug'  => 'book-133',
                'author' => 'Автор книги 133',
                'description' => 'Описание книги 133',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '7',
            ],
            [
                'title' => 'Книга 134',
                'slug'  => 'book-134',
                'author' => 'Автор книги 134',
                'description' => 'Описание книги 134',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '7',
            ],
            [
                'title' => 'Книга 135',
                'slug'  => 'book-135',
                'author' => 'Автор книги 135',
                'description' => 'Описание книги 135',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '7',
            ],
            [
                'title' => 'Книга 136',
                'slug'  => 'book-136',
                'author' => 'Автор книги 136',
                'description' => 'Описание книги 136',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '7',
            ],
            [
                'title' => 'Книга 137',
                'slug'  => 'book-137',
                'author' => 'Автор книги 137',
                'description' => 'Описание книги 137',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '7',
            ],
            [
                'title' => 'Книга 138',
                'slug'  => 'book-138',
                'author' => 'Автор книги 138',
                'description' => 'Описание книги 138',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '7',
            ],
            [
                'title' => 'Книга 139',
                'slug'  => 'book-139',
                'author' => 'Автор книги 139',
                'description' => 'Описание книги 139',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '7',
            ],
            [
                'title' => 'Книга 140',
                'slug'  => 'book-140',
                'author' => 'Автор книги 140',
                'description' => 'Описание книги 140',
                'rating' => random_int(1,50),
                'cover' => 'covers/ZcohSao03n4tbOV5gr8BYc07gZoj7Qs18IJXqkyz.png',
                'category_id' => '7',
            ],
        ]);
    }
}

