<?php
namespace Database\Seeders;

use App\Models\Books;
use App\Models\Category;
use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class BooksSeeder extends Seeder
{
    public function run()
    {
        Books::insert([
            [
                'title' => 'Книга 1',
                'slug'  => 'book-1',
                'author' => 'Автор книги 1',
                'description' => 'Описание книги 1',
                'rating' => random_int(1,50),
                'cover' => 'https://via.placeholder.com/200x150',
                'category_id' => '1',
            ],
            [
                'title' => 'Книга 2',
                'slug'  => 'book-2',
                'author' => 'Автор книги 2',
                'description' => 'Описание книги 2',
                'rating' => random_int(1,50),
                'cover' => 'https://via.placeholder.com/200x150',
                'category_id' => '1',
            ],
            [
                'title' => 'Книга 3',
                'slug'  => 'book-3',
                'author' => 'Автор книги 3',
                'description' => 'Описание книги 3',
                'rating' => random_int(1,50),
                'cover' => 'https://via.placeholder.com/200x150',
                'category_id' => '1'
            ],
            [
                'title' => 'Книга 4',
                'slug'  => 'book-4',
                'author' => 'Автор книги 4',
                'description' => 'Описание книги 4',
                'rating' => random_int(1,50),
                'cover' => 'https://via.placeholder.com/200x150',
                'category_id' => '1',
            ],
            [
                'title' => 'Книга 5',
                'slug'  => 'book-5',
                'author' => 'Автор книги 5',
                'description' => 'Описание книги 5',
                'rating' => random_int(1,50),
                'cover' => 'https://via.placeholder.com/200x150',
                'category_id' => '1',
            ],
            [
                'title' => 'Книга 6',
                'slug'  => 'book-6',
                'author' => 'Автор книги 6',
                'description' => 'Описание книги 6',
                'rating' => random_int(1,50),
                'cover' => 'https://via.placeholder.com/200x150',
                'category_id' => '1',
            ],
            [
                'title' => 'Книга 7',
                'slug'  => 'book-7',
                'author' => 'Автор книги 7',
                'description' => 'Описание книги 7',
                'rating' => random_int(1,50),
                'cover' => 'https://via.placeholder.com/200x150',
                'category_id' => '1',
            ],
            [
                'title' => 'Книга 8',
                'slug'  => 'book-8',
                'author' => 'Автор книги 8',
                'description' => 'Описание книги 8',
                'rating' => random_int(1,50),
                'cover' => 'https://via.placeholder.com/200x150',
                'category_id' => '1'
            ],
            [
                'title' => 'Книга 9',
                'slug'  => 'book-9',
                'author' => 'Автор книги 9',
                'description' => 'Описание книги 9',
                'rating' => random_int(1,50),
                'cover' => 'https://via.placeholder.com/200x150',
                'category_id' => '1',
            ],
            [
                'title' => 'Книга 10',
                'slug'  => 'book-10',
                'author' => 'Автор книги 10',
                'description' => 'Описание книги 10',
                'rating' => random_int(1,50),
                'cover' => 'https://via.placeholder.com/200x150',
                'category_id' => '1',
            ],
            [
                'title' => 'Книга 11',
                'slug'  => 'book-11',
                'author' => 'Автор книги 11',
                'description' => 'Описание книги 11',
                'rating' => random_int(1,50),
                'cover' => 'https://via.placeholder.com/200x150',
                'category_id' => '1',
            ],
            [
                'title' => 'Книга 12',
                'slug'  => 'book-12',
                'author' => 'Автор книги 12',
                'description' => 'Описание книги 12',
                'rating' => random_int(1,50),
                'cover' => 'https://via.placeholder.com/200x150',
                'category_id' => '1',
            ],
            [
                'title' => 'Книга 13',
                'slug'  => 'book-13',
                'author' => 'Автор книги 13',
                'description' => 'Описание книги 13',
                'rating' => random_int(1,50),
                'cover' => 'https://via.placeholder.com/200x150',
                'category_id' => '1'
            ],
            [
                'title' => 'Книга 14',
                'slug'  => 'book-14',
                'author' => 'Автор книги 14',
                'description' => 'Описание книги 14',
                'rating' => random_int(1,50),
                'cover' => 'https://via.placeholder.com/200x150',
                'category_id' => '1',
            ],
            [
                'title' => 'Книга 15',
                'slug'  => 'book-15',
                'author' => 'Автор книги 15',
                'description' => 'Описание книги 15',
                'rating' => random_int(1,50),
                'cover' => 'https://via.placeholder.com/200x150',
                'category_id' => '1',
            ],
            [
                'title' => 'Книга 16',
                'slug'  => 'book-16',
                'author' => 'Автор книги 16',
                'description' => 'Описание книги 16',
                'rating' => random_int(1,50),
                'cover' => 'https://via.placeholder.com/200x150',
                'category_id' => '1',
            ],
            [
                'title' => 'Книга 17',
                'slug'  => 'book-17',
                'author' => 'Автор книги 17',
                'description' => 'Описание книги 17',
                'rating' => random_int(1,50),
                'cover' => 'https://via.placeholder.com/200x150',
                'category_id' => '1',
            ],
            [
                'title' => 'Книга 18',
                'slug'  => 'book-18',
                'author' => 'Автор книги 18',
                'description' => 'Описание книги 18',
                'rating' => random_int(1,50),
                'cover' => 'https://via.placeholder.com/200x150',
                'category_id' => '1'
            ],
            [
                'title' => 'Книга 19',
                'slug'  => 'book-19',
                'author' => 'Автор книги 19',
                'description' => 'Описание книги 19',
                'rating' => random_int(1,50),
                'cover' => 'https://via.placeholder.com/200x150',
                'category_id' => '1',
            ],
            [
                'title' => 'Книга 20',
                'slug'  => 'book-20',
                'author' => 'Автор книги 20',
                'description' => 'Описание книги 20',
                'rating' => random_int(1,50),
                'cover' => 'https://via.placeholder.com/200x150',
                'category_id' => '1',
            ],
            [
                'title' => 'Книга 21',
                'slug'  => 'book-21',
                'author' => 'Автор книги 21',
                'description' => 'Описание книги 21',
                'rating' => random_int(1,50),
                'cover' => 'https://via.placeholder.com/200x150',
                'category_id' => '2',
            ],
            [
                'title' => 'Книга 22',
                'slug'  => 'book-22',
                'author' => 'Автор книги 22',
                'description' => 'Описание книги 22',
                'rating' => random_int(1,50),
                'cover' => 'https://via.placeholder.com/200x150',
                'category_id' => '2',
            ],
            [
                'title' => 'Книга 23',
                'slug'  => 'book-23',
                'author' => 'Автор книги 23',
                'description' => 'Описание книги 23',
                'rating' => random_int(1,50),
                'cover' => 'https://via.placeholder.com/200x150',
                'category_id' => '2'
            ],
            [
                'title' => 'Книга 24',
                'slug'  => 'book-24',
                'author' => 'Автор книги 24',
                'description' => 'Описание книги 24',
                'rating' => random_int(1,50),
                'cover' => 'https://via.placeholder.com/200x150',
                'category_id' => '2',
            ],
            [
                'title' => 'Книга 25',
                'slug'  => 'book-25',
                'author' => 'Автор книги 25',
                'description' => 'Описание книги 5',
                'rating' => random_int(1,50),
                'cover' => 'https://via.placeholder.com/200x150',
                'category_id' => '2',
            ],
            [
                'title' => 'Книга 26',
                'slug'  => 'book-26',
                'author' => 'Автор книги 26',
                'description' => 'Описание книги 26',
                'rating' => random_int(1,50),
                'cover' => 'https://via.placeholder.com/200x150',
                'category_id' => '2',
            ],
            [
                'title' => 'Книга 27',
                'slug'  => 'book-27',
                'author' => 'Автор книги 27',
                'description' => 'Описание книги 27',
                'rating' => random_int(1,50),
                'cover' => 'https://via.placeholder.com/200x150',
                'category_id' => '2',
            ],
            [
                'title' => 'Книга 28',
                'slug'  => 'book-28',
                'author' => 'Автор книги 28',
                'description' => 'Описание книги 28',
                'rating' => random_int(1,50),
                'cover' => 'https://via.placeholder.com/200x150',
                'category_id' => '2'
            ],
            [
                'title' => 'Книга 29',
                'slug'  => 'book-29',
                'author' => 'Автор книги 29',
                'description' => 'Описание книги 29',
                'rating' => random_int(1,50),
                'cover' => 'https://via.placeholder.com/200x150',
                'category_id' => '2',
            ],
            [
                'title' => 'Книга 30',
                'slug'  => 'book-30',
                'author' => 'Автор книги 30',
                'description' => 'Описание книги 30',
                'rating' => random_int(1,50),
                'cover' => 'https://via.placeholder.com/200x150',
                'category_id' => '2',
            ],
            [
                'title' => 'Книга 31',
                'slug'  => 'book-31',
                'author' => 'Автор книги 31',
                'description' => 'Описание книги 31',
                'rating' => random_int(1,50),
                'cover' => 'https://via.placeholder.com/200x150',
                'category_id' => '2',
            ],
            [
                'title' => 'Книга 32',
                'slug'  => 'book-32',
                'author' => 'Автор книги 32',
                'description' => 'Описание книги 32',
                'rating' => random_int(1,50),
                'cover' => 'https://via.placeholder.com/200x150',
                'category_id' => '2',
            ],
            [
                'title' => 'Книга 33',
                'slug'  => 'book-33',
                'author' => 'Автор книги 33',
                'description' => 'Описание книги 33',
                'rating' => random_int(1,50),
                'cover' => 'https://via.placeholder.com/200x150',
                'category_id' => '2'
            ],
            [
                'title' => 'Книга 34',
                'slug'  => 'book-34',
                'author' => 'Автор книги 34',
                'description' => 'Описание книги 34',
                'rating' => random_int(1,50),
                'cover' => 'https://via.placeholder.com/200x150',
                'category_id' => '2',
            ],
            [
                'title' => 'Книга 35',
                'slug'  => 'book-35',
                'author' => 'Автор книги 35',
                'description' => 'Описание книги 35',
                'rating' => random_int(1,50),
                'cover' => 'https://via.placeholder.com/200x150',
                'category_id' => '2',
            ],
            [
                'title' => 'Книга 36',
                'slug'  => 'book-36',
                'author' => 'Автор книги 36',
                'description' => 'Описание книги 36',
                'rating' => random_int(1,50),
                'cover' => 'https://via.placeholder.com/200x150',
                'category_id' => '2',
            ],
            [
                'title' => 'Книга 37',
                'slug'  => 'book-37',
                'author' => 'Автор книги 37',
                'description' => 'Описание книги 37',
                'rating' => random_int(1,50),
                'cover' => 'https://via.placeholder.com/200x150',
                'category_id' => '2',
            ],
            [
                'title' => 'Книга 38',
                'slug'  => 'book-38',
                'author' => 'Автор книги 38',
                'description' => 'Описание книги 38',
                'rating' => random_int(1,50),
                'cover' => 'https://via.placeholder.com/200x150',
                'category_id' => '2'
            ],
            [
                'title' => 'Книга 39',
                'slug'  => 'book-39',
                'author' => 'Автор книги 39',
                'description' => 'Описание книги 39',
                'rating' => random_int(1,50),
                'cover' => 'https://via.placeholder.com/200x150',
                'category_id' => '2',
            ],
            [
                'title' => 'Книга 40',
                'slug'  => 'book-40',
                'author' => 'Автор книги 40',
                'description' => 'Описание книги 40',
                'rating' => random_int(1,50),
                'cover' => 'https://via.placeholder.com/200x150',
                'category_id' => '2',
            ],
        ]);
    }
}

